new changes in password input
bildvitta/quasar-app-extension-steroids pull request #47
Opened 2020-10-21 14:29 UTC by DouglasCalora

2020-10-21 17:10 UTC, caiotarifa requested changes

2020-10-21 17:10 UTC, caiotarifa commented on src/components/PasswordInput.vue
> +      return this.$attrs['bottom-slots'] || this.$attrs['bottom-slots'] === undefined
Mas isso não vem no `$attrs`?

2020-10-21 17:10 UTC, caiotarifa commented on src/components/PasswordStrengthChecker.vue
> +      return this.value && !!this.value.match(this.pattern)
Tem que tomar um pouco de cuidado com isso na hora de submeter um formulário, em alguns casos a senha fica vazia. Ex: página de editar usuário quando não se quer atualizar a senha.

2020-10-21 18:17 UTC, DouglasCalora commented on src/components/PasswordInput.vue
> +      return this.$attrs['bottom-slots'] || this.$attrs['bottom-slots'] === undefined
pra existir ele sempre precisa ser true, mas eu preciso nao passar tb, acha que deveria passar sempre caso eu queira?

2020-10-21 18:18 UTC, DouglasCalora commented on src/components/PasswordStrengthChecker.vue
> +      return this.value && !!this.value.match(this.pattern)
nao entendi, aqui ele só vai verificar caso exista, senao ele tenta validar com um `null` e da erro

2020-10-23 15:05 UTC, caiotarifa approved these changes

2020-10-23 16:16 UTC, merged