Feature/v2.0.3
bildvitta/quasar-app-extension-steroids pull request #52
Opened 2020-11-03 20:37 UTC by DouglasCalora

## 2.0.3 (xx-xx-xxxx)

- fetures:
  - qs-search-box
  - qs-box
  - added new prop `fieldsProps` to qs-form-generator
  - added new prop `fieldProps` to qs-field
  - added new prop `iconColor` to qs-password-input
  - added new prop `bottomSlots` to qs-password-input

2020-11-03 21:41 UTC, caiotarifa requested changes

2020-11-03 21:41 UTC, caiotarifa commented on src/components/Box.vue
> +}
Por que não estamos usando a classe do Quasar para sombra?

2020-11-03 21:41 UTC, caiotarifa commented on src/components/Field.vue
> +      return { ...(profiles[type] || profiles.default), ...this.$attrs, ...this.fieldProps }
Usar o `v-bind` não resolveria?

2020-11-03 21:41 UTC, caiotarifa commented on src/components/SearchBox.vue
> +  },
Faz sentido escutar tantas coisas assim? Tenho a impressão de que daria para resolver algumas coisas sem usar `watch`.

2020-11-03 21:41 UTC, caiotarifa commented on src/components/SearchBox.vue
> +      return { maxHeight: this.maxHeight, minHeight: this.minHeight }
Por que precisamos de um mínimo e de um máximo e não apenas de uma altura?

2020-11-03 21:42 UTC, DouglasCalora commented on src/components/Box.vue
> +}
pq ela é bem diferente, ai tem varias shadows

2020-11-03 21:42 UTC, DouglasCalora commented on src/components/Field.vue
> +      return { ...(profiles[type] || profiles.default), ...this.$attrs, ...this.fieldProps }
mas ele usa ele no v-bind

2020-11-03 21:45 UTC, DouglasCalora commented on src/components/SearchBox.vue
> +  },
creio que precise...
 - search é do input
- se eu mudar dinamicamente as opções do fuse preciso repassar pra ele
- se eu mudar dinamicamente a lista, preciso repassar ela para o fuse
- sempre que n tem valor eu emito um evento, só se nesse caso eu fizer isto dentro da computada, acha que é uma boa?

2020-11-03 21:46 UTC, DouglasCalora commented on src/components/SearchBox.vue
> +      return { maxHeight: this.maxHeight, minHeight: this.minHeight }
pq assim tem mais controle, mas pode ser tb

2020-11-03 21:56 UTC, caiotarifa commented on src/components/Box.vue
> +}
Acho que é melhor usarmos o padrão do Quasar e evitar CSS.

2020-11-03 21:58 UTC, caiotarifa commented on src/components/Field.vue
> +      return { ...(profiles[type] || profiles.default), ...this.$attrs, ...this.fieldProps }
Mas passar para o componente fields-props e v-bind não é a mesma coisa? Já que você pega o $attrs, sacou?

2020-11-03 21:59 UTC, caiotarifa commented on src/components/SearchBox.vue
> +  },
Não sei, não tem um evento no Fuse para ativar essas coisas?

2020-11-03 22:01 UTC, caiotarifa commented on src/components/SearchBox.vue
> +      return { maxHeight: this.maxHeight, minHeight: this.minHeight }
Acho que precisamos de um motivo claro para ir por esse caminho. Se não tem motivo, melhor só height mesmo.

2020-11-04 13:23 UTC, DouglasCalora commented on src/components/SearchBox.vue
> +      return { maxHeight: this.maxHeight, minHeight: this.minHeight }
feito

2020-11-04 13:24 UTC, DouglasCalora commented on src/components/Box.vue
> +}
irei conversar com o lucas sobre, por hora deixarei assim

2020-11-05 19:27 UTC, caiotarifa approved these changes

2020-11-05 19:47 UTC, merged