changes header area appbar v2
bildvitta/quasar-app-extension-steroids pull request #54
Opened 2020-11-16 19:52 UTC by cassioalmeida2

2020-11-16 20:03 UTC, DouglasCalora requested changes
Está faltando o changelog.

2020-11-16 20:03 UTC, DouglasCalora commented on src/components/AppBar.vue
> +        <img :src="brand" alt="" class="qs-toolbar__brand">
temos acesso a algo que podemos utilizar no alt?

2020-11-16 20:03 UTC, DouglasCalora commented on src/components/AppBar.vue
> +        {{ title }} <q-badge v-if="hasDevelopmentBadge" align="middle" color="negative" :label="developmentBadgeLabel" />
se jogar o q-badge para baixo continua funcionando?

2020-11-17 13:38 UTC, cassioalmeida2 commented on src/components/AppBar.vue
> +        <img :src="brand" alt="" class="qs-toolbar__brand">
podemos usar o title, atualizado!

2020-11-17 13:38 UTC, cassioalmeida2 commented on src/components/AppBar.vue
> +        {{ title }} <q-badge v-if="hasDevelopmentBadge" align="middle" color="negative" :label="developmentBadgeLabel" />
funciona sim, atualizado.

2020-11-25 12:32 UTC, DouglasCalora approved these changes

2020-11-25 12:32 UTC, merged