Feature/v2.0.5
bildvitta/quasar-app-extension-steroids pull request #57
Opened 2020-12-02 13:31 UTC by DouglasCalora

## 2.0.5 (12-02-2020)

- features:
  - add new type number to field
  - new class text-xs
  - new filters to handle document masks etc
  - new ways to send columns to form-generator and grid-generator

- changed:
  - lodash version to ---> >=4.17.19 (vulnerability changes)
  - breadcrumbs font-size in mobile and remover default root
  - fixed qs-select-list bug

2020-12-02 19:17 UTC, caiotarifa requested changes

2020-12-02 19:17 UTC, caiotarifa commented on package.json
> +    "lodash": ">=4.17.19",
Por que mudou para `>=`?

2020-12-02 19:17 UTC, caiotarifa commented on src/components/SelectList.vue
> +      immediate:true
Faltou espaço.

2020-12-02 19:17 UTC, caiotarifa commented on src/css/text.scss
> +}
Tamanhos de textos não são classificados com `xs`, seguir o padrão do Quasar.

https://quasar.dev/style/typography#Headings

2020-12-02 19:17 UTC, caiotarifa commented on src/helpers/filters.js
> +}
Muito específico para o Brasil, essas definições deveriam ser estendidas e adicionadas no projeto ou em um pacote específico, não no Steroids.

2020-12-02 19:17 UTC, caiotarifa commented on src/mixins/generator.js
> +    setDefaultCol (isGridGenerator) {
Nenhum outro método abreviou coluna.

2020-12-02 19:19 UTC, caiotarifa commented on src/helpers/filters.js
> +}
Podemos manter assim por hora, mas é bom ter isso em mente.

2020-12-02 20:28 UTC, DouglasCalora commented on package.json
> +    "lodash": ">=4.17.19",
Estava mostrado falaha de vulnerabilidade, ai estava remendando colocar desta forma...

2020-12-02 20:29 UTC, DouglasCalora commented on src/css/text.scss
> +}
mas como ficaria neste caso?

2020-12-02 20:29 UTC, DouglasCalora commented on src/components/SelectList.vue
> +      immediate:true
feito

2020-12-02 20:29 UTC, DouglasCalora commented on src/helpers/filters.js
> +}
Blz, pensaremos em algo mais generico futuramente.

2020-12-02 20:30 UTC, DouglasCalora commented on src/mixins/generator.js
> +    setDefaultCol (isGridGenerator) {
é que se coloca `column` dentro da tabela tem outro signficado do que a classe `col` ainda assim, colocar `setDefaultColumn`?

2020-12-02 21:32 UTC, caiotarifa commented on src/mixins/generator.js
> +    setDefaultCol (isGridGenerator) {
`setDefaultColumn` ou `setDefaultColumnClass`

2020-12-02 21:35 UTC, caiotarifa commented on src/css/text.scss
> +}
O time de design não conseguiu utilizar nenhum dos estilos de texto que existem fazendo-se necessário criar um novo? 

Até porque `10px` é muito pequeno, chega a ser um problema de acessibilidade.

2020-12-02 21:35 UTC, caiotarifa approved these changes

2020-12-03 20:23 UTC, DouglasCalora commented on src/mixins/generator.js
> +    setDefaultCol (isGridGenerator) {
alterado para -> `setDefaultColumnClass`

2020-12-03 20:29 UTC, DouglasCalora commented on src/css/text.scss
> +}
Conversei com o lucas, vamos manter 12px pois agora nao irá quebrar com o que temos, mas testamos os 10px e não parece gerar problemas de acessibilidades, caso quebre em algum caso o breadcrumbs iremos alterar para 10px, por hora ficamos em 12.

2020-12-03 20:29 UTC, merged