feat: - QsResizer changed baseURL `'https://d17ouzaofz81f3.cloudfront…
bildvitta/quasar-app-extension-steroids pull request #73
Opened 2022-04-04 17:59 UTC by felipejuzo02

….net/'` to `'https://image-resize.nave.dev/'`

2022-04-04 19:44 UTC, DouglasCalora requested changes

2022-04-04 19:44 UTC, DouglasCalora commented on changelog.md
> +## 1.3.0 - 2022-04-04
Quando abrir PR o mais correto é adicinar `## Unreleased`, e não alterar as versões no package.json, fazemos isto na hora de publicar, ai por exemplo não é 1.3.0, mas sim 1.2.1, você não adicionou nenhum novo recurso.

2022-04-05 13:05 UTC, felipejuzo02 commented on changelog.md
> +## 1.3.0 - 2022-04-04
alterado

2022-04-05 13:26 UTC, DouglasCalora approved these changes

2022-04-05 13:26 UTC, merged