Feature/v1 creation slot in qsfilters
bildvitta/quasar-app-extension-steroids pull request #77
Opened 2022-05-18 14:24 UTC by felipejuzo02

2022-05-18 18:46 UTC, eliasassuncao requested changes

2022-05-18 18:46 UTC, eliasassuncao commented on src/components/Filters.vue
> +    <slot name="beforeSearch" :context="context" :filter="filter" :filters="activeFilters" :removeFilter="removeFilter" />
os nomes dos slots por padrão usamos kebab-case, então seria before-search

2022-05-18 20:18 UTC, felipejuzo02 commented on src/components/Filters.vue
> +    <slot name="beforeSearch" :context="context" :filter="filter" :filters="activeFilters" :removeFilter="removeFilter" />
alterado

2022-05-19 19:19 UTC, eliasassuncao approved these changes

2022-05-19 19:19 UTC, eliasassuncao commented on changelog.md
> +- Creation of `beforeSearch` and `AfterSearch` in `QsFilter`
trocar pra `before-search` e `after-search`

2022-05-24 19:17 UTC, merged